# Generated by Django 3.0.7 on 2020-06-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('total_cases', models.IntegerField(blank=True, max_length=10)),
                ('new_cases', models.IntegerField(blank=True, max_length=10)),
                ('total_deaths', models.IntegerField(blank=True, max_length=10)),
                ('new_deaths', models.IntegerField(blank=True, max_length=10)),
                ('total_recovered', models.IntegerField(blank=True, max_length=10)),
                ('new_recovered', models.IntegerField(blank=True, max_length=10)),
                ('active_cases', models.IntegerField(blank=True, max_length=10)),
                ('serious_cases', models.IntegerField(blank=True, max_length=10)),
                ('population', models.IntegerField(blank=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
