# Generated by Django 3.0.7 on 2020-06-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartcovid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='active_cases',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='new_cases',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='new_deaths',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='new_recovered',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='serious_cases',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_cases',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_deaths',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='total_recovered',
            field=models.IntegerField(blank=True),
        ),
    ]
